name: Build and Use GraalVM LibGraal with SapMachine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up General Environment Variables
      shell: bash
      run: |
        echo "Setting up general environment variables..."
        echo "MX_GIT_CACHE=refcache" >> ${GITHUB_ENV}
        echo "MX_PYTHON=python3" >> ${GITHUB_ENV}
        echo "LANG=en_US.UTF-8" >> ${GITHUB_ENV}

    - name: Install Other Dependencies
      run: |
        echo "Installing other dependencies..."
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libffi-dev \
                                libasound2-dev libcups2-dev \
                                libx11-dev libxext-dev \
                                libxrender-dev libxrandr-dev \
                                libxtst-dev libxt-dev

    - name: Clone mx Tool and Set MX_PATH
      run: |
        echo "Cloning mx tool..."
        git clone https://github.com/graalvm/mx.git ${GITHUB_WORKSPACE}/mx
        cd ${GITHUB_WORKSPACE}/mx

        # Set MX_PATH after mx tool is available
        echo "MX_PATH=${GITHUB_WORKSPACE}/mx" >> ${GITHUB_ENV}

    - name: Clone and Build SapMachine JDK from Source
      run: |
        echo "Cloning SapMachine repository..."
        git clone --branch sapmachine-21.0.4 --depth 1 https://github.com/SAP/SapMachine.git
        cd SapMachine

        echo "Setting executable permissions for configure script..."
        chmod +x ./configure

        echo "Configuring and building SapMachine JDK..."
        ./configure
        make graal-builder-image

        export JAVA_HOME=$(pwd)/build/linux-x86_64-server-release/images/graal-builder-jdk
        echo "JAVA_HOME=${JAVA_HOME}" >> ${GITHUB_ENV}

        # Verifying directories and outputs
        echo "Verifying build directory contents:"
        ls -altr ${JAVA_HOME}

    - name: Verify SapMachine JDK Installation
      run: |
        echo "Verifying SapMachine JDK installation..."
        ${JAVA_HOME}/bin/java -version

    - name: Clone GraalVM Source
      run: |
        echo "Cloning GraalVM source from graalvm-community-jdk21u repository..."
        git clone https://github.com/graalvm/graalvm-community-jdk21u.git ${GITHUB_WORKSPACE}/graalvm-community-jdk21u

    - name: Build GraalVM LibGraal
      shell: bash
      run: |
        echo "Changing to the 'vm' directory to run 'mx'..."
        cd ${GITHUB_WORKSPACE}/graalvm-community-jdk21u/vm 

        echo "Building GraalVM LibGraal..."
        ${MX_PATH}/mx --env libgraal build
        
        echo "Setting GRAALVM_HOME using graalvm-home with libgraal environment..."
        export GRAALVM_HOME=$(${MX_PATH}/mx --env libgraal graalvm-home)
        echo "GRAALVM_HOME=${GRAALVM_HOME}" >> ${GITHUB_ENV}

        echo "Listing contents of GRAALVM_HOME:"
        ls -l ${GRAALVM_HOME}

        echo "Verifying critical files in GRAALVM_HOME/lib:"
        ls -altr ${GRAALVM_HOME}/lib/libjvmcicompiler.so || echo "Warning: libjvmcicompiler.so not found in expected location"

    - name: Set JAVA_HOME to GRAALVM_HOME
      run: |
        echo "Setting JAVA_HOME to GRAALVM_HOME directory..."
        export JAVA_HOME=${GRAALVM_HOME}
        echo "JAVA_HOME=${JAVA_HOME}" >> ${GITHUB_ENV}

    - name: Verify Build
      run: |
        echo "Verifying Java installation in GRAALVM_HOME directory..."
        ${JAVA_HOME}/bin/java -version

    - name: Verify Graal JIT Usage with JVM Flags
      shell: bash
      run: |
        echo "Verifying Graal JIT usage with JVM flags..."
        ${JAVA_HOME}/bin/java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -XX:+PrintFlagsFinal \
          -version | grep -iE "UseGraalJIT|EnableJVMCI|JVMCI"

    - name: Compile and Run Microbenchmark to Test Graal JIT
      shell: bash
      run: |
        echo "Compiling and running microbenchmark to test Graal JIT..."
        cat <<EOF > GraalJITTest.java
        public class GraalJITTest {
            public static void main(String[] args) {
                for (int i = 0; i < 100_000; i++) {
                    compute(i);
                }
            }

            public static long compute(int x) {
                long result = 0;
                for (int i = 0; i < 10_000; i++) {
                    result += Math.sqrt(x * i);
                }
                return result;
            }
        }
        EOF

        ${JAVA_HOME}/bin/javac GraalJITTest.java
        ${JAVA_HOME}/bin/java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -Dgraal.PrintCompilation=true \
          GraalJITTest

    - name: Output hs_err Logs if Exist
      shell: bash
      run: |
        echo "Checking for hs_err log files..."
        find ${GITHUB_WORKSPACE} -type f -name 'hs_err_pid*.log' -exec cat {} \; || echo "No hs_err log files found."

    - name: Create Archive of GRAALVM_HOME
      run: |
        echo "Creating a tar.gz archive of GRAALVM_HOME..."
        tar -czvf ${GITHUB_WORKSPACE}/graalvm-build.tar.gz -C ${GRAALVM_HOME} .
        echo "Listing contents of ${GITHUB_WORKSPACE} to verify archive creation..."
        ls -al ${GITHUB_WORKSPACE}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: graalvm-build
        path: ${GITHUB_WORKSPACE}/graalvm-build.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: graalvm-build
        path: ./

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: "graalvm-release-${{ github.run_number }}"
        release_name: "GraalVM Release ${{ github.run_number }}"
        body: "This is an automated release of the GraalVM build."
        draft: false
        prerelease: false

    - name: Upload GraalVM Build Archive as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./graalvm-build.tar.gz"
        asset_name: "graalvm-build.tar.gz"
        asset_content_type: "application/gzip"
