name: Build and Release GraalVM with Native Image and LibGraal using SapMachine

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Ensures token can create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up General Environment Variables
      shell: bash
      run: |
        echo "Setting up general environment variables..."
        echo "MX_GIT_CACHE=refcache" >> ${GITHUB_ENV}
        echo "MX_PYTHON=python3" >> ${GITHUB_ENV}
        echo "LANG=en_US.UTF-8" >> ${GITHUB_ENV}

    - name: Install Other Dependencies
      run: |
        echo "Installing other dependencies..."
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libffi-dev \
                                libasound2-dev libcups2-dev \
                                libx11-dev libxext-dev \
                                libxrender-dev libxrandr-dev \
                                libxtst-dev libxt-dev \
                                libssl-dev libz-dev

    - name: Clone mx Tool and Set MX_PATH
      run: |
        echo "Cloning mx tool..."
        git clone https://github.com/graalvm/mx.git ${GITHUB_WORKSPACE}/mx
        cd ${GITHUB_WORKSPACE}/mx

        # Set MX_PATH after mx tool is available
        echo "MX_PATH=${GITHUB_WORKSPACE}/mx" >> ${GITHUB_ENV}

    - name: Check if SapMachine Artifact Exists in Release
      id: check_sapmachine_release
      run: |
        echo "Checking if SapMachine build artifact exists in GitHub release..."
        RELEASE_TAG="sapmachine-${GITHUB_SHA}"
        RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG}"
        
        # Check if release exists
        response=$(curl -s -o /dev/null -w "%{http_code}" ${RELEASE_URL})
        
        if [ "$response" -eq 200 ]; then
          echo "Release found. Fetching asset URL for SapMachine build artifact."
          # Get the download URL for the artifact
          asset_url=$(curl -s ${RELEASE_URL} | jq -r '.assets[] | select(.name=="sapmachine-${GITHUB_SHA}.tar.gz") | .browser_download_url')
          
          if [ -n "$asset_url" ]; then
            echo "SapMachine artifact found. Setting ASSET_URL."
            echo "ASSET_URL=${asset_url}" >> $GITHUB_ENV
          else
            echo "No asset found in release. Proceeding with build."
            echo "ASSET_URL=" >> $GITHUB_ENV
          fi
        else
          echo "Release not found. Proceeding with build."
          echo "ASSET_URL=" >> $GITHUB_ENV
        fi

    - name: Clone and Build SapMachine JDK from Source
      if: ${{ env.ASSET_URL == '' }}
      run: |
        echo "Cloning SapMachine repository..."
        git clone --branch sapmachine-21.0.5 --depth 1 https://github.com/SAP/SapMachine.git
        cd SapMachine

        echo "Setting executable permissions for configure script..."
        chmod +x ./configure

        echo "Configuring and building SapMachine JDK..."
        ./configure
        make graal-builder-image

        export JAVA_HOME=$(pwd)/build/linux-x86_64-server-release/images/graal-builder-jdk
        echo "JAVA_HOME=${JAVA_HOME}" >> ${GITHUB_ENV}

        # Creating artifact tar.gz to be reused
        echo "Creating SapMachine artifact..."
        tar -czf /tmp/sapmachine-${GITHUB_SHA}.tar.gz -C $(pwd)/build/linux-x86_64-server-release/images .

        # Verifying build artifact
        echo "Verifying artifact..."
        ls -altr /tmp/sapmachine-${GITHUB_SHA}.tar.gz

    - name: Upload SapMachine Build Artifact to Release
      if: ${{ env.ASSET_URL == '' }}
      run: |
        echo "Creating new GitHub release and uploading SapMachine artifact..."
        RELEASE_TAG="sapmachine-${GITHUB_SHA}"
        RELEASE_NAME="SapMachine Build ${GITHUB_SHA}"
        # Create a new release
        release_id=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name":"'"${RELEASE_TAG}"'","name":"'"${RELEASE_NAME}"'"}' \
          https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.id')
          
        # Upload the artifact
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/gzip" \
          --data-binary @/tmp/sapmachine-${GITHUB_SHA}.tar.gz \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${release_id}/assets?name=sapmachine-${GITHUB_SHA}.tar.gz"

    - name: Download SapMachine Build Artifact if Exists
      if: ${{ env.ASSET_URL != '' }}
      run: |
        echo "Downloading SapMachine build artifact from release..."
        curl -L ${{ env.ASSET_URL }} -o /tmp/sapmachine-${GITHUB_SHA}.tar.gz

    - name: Extract SapMachine Artifact
      if: ${{ env.ASSET_URL != '' }}
      run: |
        echo "Extracting SapMachine artifact..."
        mkdir -p ${GITHUB_WORKSPACE}/sapmachine
        tar -xzf /tmp/sapmachine-${GITHUB_SHA}.tar.gz -C ${GITHUB_WORKSPACE}/sapmachine

    - name: Clone GraalVM Source
      run: |
        echo "Cloning GraalVM source from graalvm-community-jdk21u repository..."
        git clone https://github.com/graalvm/graalvm-community-jdk21u.git ${GITHUB_WORKSPACE}/graalvm-community-jdk21u

    - name: Build GraalVM with LibGraal and Native Image
      shell: bash
      run: |
        echo "Changing to the 'vm' directory to run 'mx'..."
        cd ${GITHUB_WORKSPACE}/graalvm-community-jdk21u/vm 

        echo "Building GraalVM with LibGraal, Native Image, and additional components..."
        ${MX_PATH}/mx --native=native-image,lib:jvmcicompiler,lib:native-image-agent,lib:native-image-diagnostics-agent --components="Native Image,LibGraal,svml" build

        echo "Setting GRAALVM_HOME using graalvm-home with libgraal,native-image environment..."
        export GRAALVM_HOME=$(${MX_PATH}/mx --native=native-image,lib:jvmcicompiler,lib:native-image-agent,lib:native-image-diagnostics-agent --components="Native Image,LibGraal,svml" graalvm-home)
        echo "GRAALVM_HOME=${GRAALVM_HOME}" >> ${GITHUB_ENV}

    - name: Set JAVA_HOME to GRAALVM_HOME
      run: |
        echo "Setting JAVA_HOME to GRAALVM_HOME directory..."
        export JAVA_HOME=${GRAALVM_HOME}
        echo "JAVA_HOME=${JAVA_HOME}" >> ${GITHUB_ENV}

    - name: Verify GraalVM Installation
      run: |
        echo "Verifying GraalVM installation..."
        ${JAVA_HOME}/bin/java -version

    - name: Compile and Run Native Image Test
      shell: bash
      run: |
        echo "Testing native image compilation by creating a HelloWorld binary..."
        cat <<EOF > HelloWorld.java
        public class HelloWorld {
            public static void main(String[] args) {
                System.out.println("Hello, GraalVM Native Image!");
            }
        }
        EOF

        # Compile to a native binary using native-image
        ${GRAALVM_HOME}/bin/native-image HelloWorld

        # Run the generated native executable
        echo "Running the native executable to confirm it works..."
        ./helloworld

    - name: Verify Graal JIT Usage with JVM Flags
      shell: bash
      run: |
        echo "Verifying Graal JIT usage with JVM flags..."
        ${JAVA_HOME}/bin/java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -XX:+PrintFlagsFinal \
          -version | grep -iE "UseGraalJIT|EnableJVMCI|JVMCI"

    - name: Compile and Run Microbenchmark to Test Graal JIT
      shell: bash
      run: |
        echo "Compiling and running microbenchmark to test Graal JIT..."
        cat <<EOF > GraalJITTest.java
        public class GraalJITTest {
            public static void main(String[] args) {
                for (int i = 0; i < 100_000; i++) {
                    compute(i);
                }
            }

            public static long compute(int x) {
                long result = 0;
                for (int i = 0; i < 10_000; i++) {
                    result += Math.sqrt(x * i);
                }
                return result;
            }
        }
        EOF

        ${JAVA_HOME}/bin/javac GraalJITTest.java
        ${JAVA_HOME}/bin/java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -Dgraal.PrintCompilation=true \
          GraalJITTest

    - name: Create GraalVM tar.gz Archive
      shell: bash
      run: |
        echo "Creating tar.gz archive of GraalVM..."
        tar -czf /tmp/graalvm-build.tar.gz -C ${GRAALVM_HOME} .

    - name: Upload Artifact (GraalVM Build)
      uses: actions/upload-artifact@v4
      with:
        name: graalvm-build
        path: /tmp/graalvm-build.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download GraalVM Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: graalvm-build
        path: /tmp

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "graalvm-release-${{ github.run_number }}"
        release_name: "GraalVM Build Release ${{ github.run_number }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/graalvm-build.tar.gz
        asset_name: graalvm-build.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
