name: Build and Use GraalVM LibGraal with SapMachine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "Setting environment variables..."
        echo "LABSJDK_HOME=${{ github.workspace }}/jdk-dl" >> ${GITHUB_ENV}
        echo "MX_GIT_CACHE=refcache" >> ${GITHUB_ENV}
        echo "MX_PATH=${{ github.workspace }}/mx" >> ${GITHUB_ENV}
        echo "MX_PYTHON=python3" >> ${GITHUB_ENV}
        echo "LANG=en_US.UTF-8" >> ${GITHUB_ENV}

    - name: Set up SAPMachine JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '21'

    - name: Verify SAPMachine JDK Installation
      run: |
        echo "Verifying SAPMachine JDK installation..."
        java -version  # Output SAPMachine JDK version to confirm installation

    - name: Clone GraalVM Source
      run: |
        echo "Cloning GraalVM source..."
        git clone --depth 1 https://github.com/oracle/graal.git

    - name: Clone mx Tool
      run: |
        echo "Cloning mx tool..."
        git clone --depth 1 https://github.com/graalvm/mx.git
        echo "$(pwd)/mx" >> $GITHUB_PATH  # Add mx to PATH for all steps

    - name: Install Other Dependencies
      run: |
        echo "Installing other dependencies..."
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libffi-dev jq

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Update mx Cache
      uses: actions/cache@v4
      with:
        path: ~/.mx
        key: ${{ runner.os }}-mx-${{ hashFiles('**/suite.py') }}
        restore-keys: ${{ runner.os }}-mx-

    - name: Fetch LabsJDK 21
      shell: bash
      run: |
        echo "Fetching LabsJDK 21..."
        mkdir -p jdk-dl
        echo "${MX_PATH}/mx fetch-jdk --jdk-id labsjdk-ce-21 --to jdk-dl"
        ${MX_PATH}/mx fetch-jdk --jdk-id labsjdk-ce-21 --to jdk-dl
        export LABSJDK_HOME=$(find ${GITHUB_WORKSPACE}/jdk-dl -maxdepth 1 -type d -name 'labsjdk-*')
        echo "LABSJDK_HOME=${LABSJDK_HOME}" >> ${GITHUB_ENV}

    - name: Build GraalVM LibGraal
      shell: bash
      run: |
        echo "Building GraalVM LibGraal..."
        cd graal/vm
        export JVMCI_VERSION_CHECK="ignore"
        
        # Build libgraal with the --env libgraal flag
        echo "Command: ${MX_PATH}/mx --env libgraal --java-home=${LABSJDK_HOME} build"
        ${MX_PATH}/mx --env libgraal --java-home=${LABSJDK_HOME} build
        
        # Set GRAALVM_HOME to the exact location output by graalvm-home with --env libgraal
        echo "Setting GRAALVM_HOME using graalvm-home with libgraal environment..."
        export GRAALVM_HOME=$(${MX_PATH}/mx --env libgraal --java-home=${LABSJDK_HOME} graalvm-home)
        echo "GRAALVM_HOME=${GRAALVM_HOME}" >> ${GITHUB_ENV}

        # Log the contents of the build directories for verification
        echo "Listing contents of LABSJDK_HOME:"
        ls -l ${LABSJDK_HOME}

        echo "Listing contents of GRAALVM_HOME:"
        ls -l ${GRAALVM_HOME}
        
        echo "Listing contents of GRAALVM_HOME/lib:"
        ls -altr ${GRAALVM_HOME}/lib/*

    - name: Copy libjvmcicompiler.so to SapMachine JDK
      shell: bash
      run: |
        echo "Copying libjvmcicompiler.so to the SapMachine JDK lib directory..."
        LIBGRAAL_PATH="${GITHUB_WORKSPACE}/graal/sdk/mxbuild/linux-amd64/GRAALVM_LIBGRAAL_JAVA21/graalvm-libgraal-openjdk-21.0.2+13.1/lib/libjvmcicompiler.so"
        SAP_JDK_LIB_DIR="/opt/hostedtoolcache/Java_SapMachine_jdk/21.0.5/x64/lib"
        
        if [ -f "$LIBGRAAL_PATH" ]; then
          sudo cp "$LIBGRAAL_PATH" "$SAP_JDK_LIB_DIR"
          echo "libjvmcicompiler.so successfully copied to ${SAP_JDK_LIB_DIR}"
        else
          echo "libjvmcicompiler.so not found at ${LIBGRAAL_PATH}"
          exit 1
        fi

    - name: Verify Build
      run: |
        cd graal/vm
        echo "Verifying mx version and GraalVM home..."
        echo "Command: ${MX_PATH}/mx --version"
        ${MX_PATH}/mx --version
        echo "Command: ${MX_PATH}/mx graalvm-show"
        ${MX_PATH}/mx graalvm-show
        echo "Command: ${MX_PATH}/mx graalvm-home"
        ${MX_PATH}/mx graalvm-home
        echo "Command: ls ${GRAALVM_HOME}"
        ls ${GRAALVM_HOME}
        
        echo "Command: ${GRAALVM_HOME}/bin/java -version"
        ${GRAALVM_HOME}/bin/java -version

    - name: Verify Graal JIT Usage with JVM Flags
      shell: bash
      run: |
        echo "Verifying Graal JIT usage with JVM flags..."
        echo "Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseGraalJIT -XX:+PrintFlagsFinal -version"
        java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -XX:+PrintFlagsFinal \
          -version | grep -iE "UseGraalJIT|EnableJVMCI|JVMCI"

    - name: Compile and Run Microbenchmark to Test Graal JIT
      shell: bash
      run: |
        echo "Compiling and running microbenchmark to test Graal JIT..."
        # Write a Java microbenchmark to verify Graal JIT compilation
        echo "Writing GraalJITTest.java..."
        cat <<EOF > GraalJITTest.java
        public class GraalJITTest {
            public static void main(String[] args) {
                for (int i = 0; i < 100_000; i++) {
                    compute(i);
                }
            }

            public static long compute(int x) {
                long result = 0;
                for (int i = 0; i < 10_000; i++) {
                    result += Math.sqrt(x * i);
                }
                return result;
            }
        }
        EOF

        # Compile the test
        echo "Compiling GraalJITTest.java..."
        javac GraalJITTest.java

        # Run with Graal-specific logging to verify Graal JIT usage
        echo "Running GraalJITTest with Graal JIT enabled..."
        echo "Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseGraalJIT -Dgraal.PrintCompilation=true GraalJITTest"
        java \
          -XX:+UnlockExperimentalVMOptions \
          -XX:+UseGraalJIT \
          -Dgraal.PrintCompilation=true \
          GraalJITTest
