name: Build and Use GraalVM LibGraal with SapMachine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "Setting environment variables..."
        echo "LABSJDK_HOME=${{ github.workspace }}/jdk-dl" >> ${GITHUB_ENV}
        echo "MX_GIT_CACHE=refcache" >> ${GITHUB_ENV}
        echo "MX_PATH=${{ github.workspace }}/mx" >> ${GITHUB_ENV}
        echo "MX_PYTHON=python3" >> ${GITHUB_ENV}
        echo "LANG=en_US.UTF-8" >> ${GITHUB_ENV}

    - name: Set up SAPMachine JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '21.0.4'

    - name: Verify SAPMachine JDK Installation
      run: |
        echo "Verifying SAPMachine JDK installation..."
        java -version  # Output SAPMachine JDK version to confirm installation

    - name: Clone GraalVM Source
      run: |
        echo "Cloning GraalVM source from graalvm-community-jdk21u release vm-23.1.3..."
        git clone --depth 1 --branch vm-23.1.3 https://github.com/graalvm/graalvm-community-jdk21u.git graal

    - name: Clone mx Tool
      run: |
        echo "Cloning mx tool..."
        git clone --depth 1 https://github.com/graalvm/mx.git
        echo "$(pwd)/mx" >> $GITHUB_PATH  # Add mx to PATH for all steps

    # [rest of your script continues as is...]
