name: Build GraalVM from Source

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "GRAALVM_HOME=${{ github.workspace }}/graalvm" >> ${GITHUB_ENV}
        echo "LABSJDK_HOME=${{ github.workspace }}/labsjdk" >> ${GITHUB_ENV}
        echo "MX_GIT_CACHE=refcache" >> ${GITHUB_ENV}
        echo "MX_PATH=${{ github.workspace }}/mx" >> ${GITHUB_ENV}
        echo "MX_PYTHON=python3" >> ${GITHUB_ENV}
        echo "LANG=en_US.UTF-8" >> ${GITHUB_ENV}

    - name: Clone GraalVM Source
      run: |
        git clone --depth 1 https://github.com/oracle/graal.git graalvm

    - name: Clone mx Tool
      run: |
        git clone --depth 1 https://github.com/graalvm/mx.git
        echo "$(pwd)/mx" >> $GITHUB_PATH  # Add mx to PATH for all steps

    - name: Install Other Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libffi-dev jq

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Use the latest available Python 3

    - name: Update mx Cache
      uses: actions/cache@v4
      with:
        path: ~/.mx
        key: ${{ runner.os }}-mx-${{ hashFiles('**/suite.py') }}
        restore-keys: ${{ runner.os }}-mx-

    - name: Fetch Latest LabsJDK
      shell: bash
      run: |
        mkdir jdk-dl
        # Use the latest version of LabsJDK
        ${MX_PATH}/mx fetch-jdk --jdk-id labsjdk-ce-latest --to jdk-dl --alias ${LABSJDK_HOME}

    - name: Build GraalVM JDK
      shell: bash
      run: |
        cd graalvm/substratevm
        # Set JVMCI_VERSION_CHECK to ignore (if necessary)
        export JVMCI_VERSION_CHECK="ignore"
        ${MX_PATH}/mx --java-home=${LABSJDK_HOME} build
        ln -s $(${MX_PATH}/mx --java-home=${LABSJDK_HOME} graalvm-home) ${GRAALVM_HOME}
        ${GRAALVM_HOME}/bin/native-image --version

    - name: Set up JAVA_HOME with SapMachine (Optional)
      if: ${{ inputs.java-version }} != ''
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '${{ inputs.java-version }}'

    - name: Verify Build
      run: |
        cd graalvm/compiler
        ${MX_PATH}/mx --version
